"""Context-aware explanation engine.

Generates tailored explanations based on:
- the selected text
- the surrounding document context
- the reader's familiarity profile
- the document's concept dependency graph

For MVP, explanations are generated by mock templates. The interface
is designed for drop-in LLM replacement.
"""

from dataclasses import dataclass


@dataclass
class Explanation:
    selected_text: str
    mode: str  # "quick", "deep", "prerequisites", "why_it_matters"
    content: str
    related_concepts: list[str]


def _reader_level_label(level: int) -> str:
    """Convert numeric familiarity to a readable label."""
    return {
        0: "unfamiliar",
        1: "vaguely familiar",
        2: "basically familiar",
        3: "well-versed",
    }.get(level, "unfamiliar")


def _find_relevant_concepts(
    selected_text: str,
    concepts: list[dict],
) -> list[dict]:
    """Find concepts that appear in or relate to the selected text."""
    text_lower = selected_text.lower()
    relevant = []
    for concept in concepts:
        name = concept.get("name", "").lower()
        if name in text_lower or any(
            p.lower() in text_lower
            for p in concept.get("prerequisites", [])
        ):
            relevant.append(concept)
    return relevant


def generate_explanation(
    selected_text: str,
    surrounding_text: str,
    mode: str,
    reader_profile: dict[str, int],
    concepts: list[dict],
    dependency_graph: dict[str, list[str]],
) -> Explanation:
    """Generate a context-aware explanation for selected text.

    This is the core function. For MVP it returns template-based
    responses. Replace the body with an LLM call for production:

        prompt = build_prompt(selected_text, surrounding_text, mode,
                              reader_profile, concepts, dependency_graph)
        return call_llm(prompt)

    Args:
        selected_text: The text the user highlighted.
        surrounding_text: A few paragraphs around the selection for context.
        mode: One of "quick", "deep", "prerequisites", "why_it_matters".
        reader_profile: Concept name -> familiarity level (0-3).
        concepts: List of concept dicts from concept extraction.
        dependency_graph: Concept name -> list of prerequisite names.
    """
    relevant = _find_relevant_concepts(selected_text, concepts)
    related_names = [c["name"] for c in relevant]

    # Determine the reader's overall level for relevant concepts
    levels = [reader_profile.get(name, 0) for name in related_names]
    avg_level = sum(levels) / len(levels) if levels else 1

    # Adapt tone based on reader level
    if avg_level < 1:
        tone = "beginner-friendly"
        depth = "Use simple language. Define key terms."
    elif avg_level < 2.5:
        tone = "intermediate"
        depth = "Assume basic familiarity. Focus on connections."
    else:
        tone = "advanced"
        depth = "Be concise. Highlight nuances and implications."

    # Build prerequisite chain
    prereq_chain: list[str] = []
    for name in related_names:
        prereq_chain.extend(dependency_graph.get(name, []))
    prereq_chain = list(dict.fromkeys(prereq_chain))  # dedupe, preserve order

    # Generate response based on mode
    # TODO: Replace with LLM call. The prompt would include:
    #   - selected_text, surrounding_text
    #   - tone, depth instructions
    #   - relevant concepts and their prerequisites
    #   - reader_profile for fine-grained adaptation

    if mode == "quick":
        content = _mock_quick(selected_text, tone, related_names)
    elif mode == "deep":
        content = _mock_deep(selected_text, tone, related_names, prereq_chain)
    elif mode == "prerequisites":
        content = _mock_prerequisites(selected_text, prereq_chain, reader_profile)
    elif mode == "why_it_matters":
        content = _mock_why_matters(selected_text, tone, related_names)
    else:
        content = _mock_quick(selected_text, tone, related_names)

    return Explanation(
        selected_text=selected_text,
        mode=mode,
        content=content,
        related_concepts=related_names,
    )


def _mock_quick(text: str, tone: str, concepts: list[str]) -> str:
    concept_ref = f" This relates to: {', '.join(concepts)}." if concepts else ""
    if tone == "beginner-friendly":
        return (
            f"This passage introduces an important idea. In simple terms, "
            f"it describes a foundational concept that many later arguments "
            f"build upon.{concept_ref}"
        )
    elif tone == "advanced":
        return (
            f"This passage engages with a nuanced point. Given your background, "
            f"note how it connects to broader theoretical frameworks.{concept_ref}"
        )
    return (
        f"This passage discusses a concept worth pausing on. "
        f"It builds on ideas you may partially know.{concept_ref}"
    )


def _mock_deep(
    text: str, tone: str, concepts: list[str], prereqs: list[str],
) -> str:
    parts = [f"Let's unpack this passage in detail."]
    if concepts:
        parts.append(f"Key concepts involved: {', '.join(concepts)}.")
    if prereqs:
        parts.append(
            f"This builds on: {', '.join(prereqs)}. "
            f"Understanding these will help this passage click."
        )
    if tone == "beginner-friendly":
        parts.append(
            "Think of it this way: the author is constructing an argument "
            "step by step. Each term has a specific meaning in this context "
            "that may differ from everyday usage."
        )
    elif tone == "advanced":
        parts.append(
            "The author is making a precise move here. Consider how this "
            "fits into the larger argumentative structure and what it implies "
            "for the conclusions that follow."
        )
    return " ".join(parts)


def _mock_prerequisites(
    text: str, prereqs: list[str], profile: dict[str, int],
) -> str:
    if not prereqs:
        return (
            "This passage is fairly self-contained. No major prerequisites "
            "are needed beyond what you've already read."
        )

    unknown = [p for p in prereqs if profile.get(p, 0) < 2]
    known = [p for p in prereqs if profile.get(p, 0) >= 2]

    parts = ["Before reading this, it helps to understand:"]
    if unknown:
        parts.append(f"  Concepts to review: {', '.join(unknown)}.")
    if known:
        parts.append(f"  You're already familiar with: {', '.join(known)}.")
    return " ".join(parts)


def _mock_why_matters(text: str, tone: str, concepts: list[str]) -> str:
    concept_ref = (
        f" specifically in relation to {', '.join(concepts)}"
        if concepts else ""
    )
    if tone == "beginner-friendly":
        return (
            f"This matters because it lays the groundwork for understanding "
            f"the author's main argument{concept_ref}. Without grasping this "
            f"point, later sections will be harder to follow."
        )
    return (
        f"This is significant because it represents a key move in the "
        f"author's argument{concept_ref}. It connects to central themes "
        f"that recur throughout the text."
    )


def detect_difficult_passage(
    page_text: str,
    reader_profile: dict[str, int],
    concepts: list[dict],
) -> str | None:
    """Check if a page contains concepts the reader is unfamiliar with.

    Returns a subtle nudge message if so, or None if the page is fine.
    Used for the occasional "you might want context" prompt.
    """
    text_lower = page_text.lower()
    unfamiliar_concepts = []

    for concept in concepts:
        name = concept.get("name", "")
        if name.lower() in text_lower and reader_profile.get(name, 0) < 2:
            unfamiliar_concepts.append(name)

    if unfamiliar_concepts:
        names = ", ".join(unfamiliar_concepts[:3])
        return (
            f"This section touches on {names} — concepts you may want "
            f"a quick refresher on before continuing."
        )

    return None
